{% set name = "xraydb" %}
{% set version = "4.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c8d996ff84976db3d602841677425bab44cb02916ccb596fa7a102ba509d0bda

build:
  number: 0
  noarch: python
  script: cd python && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - numpy
    - scipy
    - sqlalchemy

test:
  imports:
    - xraydb

about:
  home: https://github.com/xraypy/XrayDB
  license: Public Domain
  license_family: OTHER
  license_file: LICENSE
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
  doc_url: https://xraypy.github.io/XrayDB/
  dev_url: https://github.com/xraypy/XrayDB/

extra:
  recipe-maintainers:
    - newville
