{% set name = "xraydb" %}
{% set version = "4.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: aed02e9638521b2c3116ebadb05f97b43480edf6f161db589141fb0f1ea41273

build:
  number: 0
  noarch: python
  script: cd python && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - numpy
    - scipy
    - sqlalchemy

test:
  imports:
    - xraydb

about:
  home: https://github.com/xraypy/XrayDB
  license: Public Domain
  license_family: OTHER
  license_file: LICENSE
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
  doc_url: https://xraypy.github.io/XrayDB/
  dev_url: https://github.com/xraypy/XrayDB/

extra:
  recipe-maintainers:
    - newville
