{% set name = "XrayDB" %}
{% set version = "4.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: aed02e9638521b2c3116ebadb05f97b43480edf6f161db589141fb0f1ea41273a

build:
  number: 1
  noarch: python
  script: cd python && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy
    - scipy
    - sqlalchemy >= 2.0.1
    - platformdirs
    - setuptools
    - packaging

test:
  requires:
    - python >=3.9
  imports:
    - xraydb

about:
  home: https://github.com/xraypy/XrayDB
  license: Public Domain
  license_family: OTHER
  license_file: LICENSE
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
  doc_url: https://xraypy.github.io/XrayDB/
  dev_url: https://github.com/xraypy/XrayDB/

extra:
  recipe-maintainers:
    - newville
