{% set name = "xraydb" %}
{% set version = "4.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 99d20c4c3d7d000f9acf75a86f8e572a6b011ada767cb6add6e23713d859ff69

build:
  number: 0
  noarch: python
  script: cd python && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - sqlalchemy

test:
  imports:
    - xraydb

about:
  home: https://github.com/xraypy/XrayDB
  license: Public Domain
  license_family: OTHER
  license_file: LICENSE
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
  doc_url: https://xraypy.github.io/XrayDB/
  dev_url: https://github.com/xraypy/XrayDB/

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
