{% set name = "XrayDB" %}
{% set version = "4.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 28b94420a6a1ab1beb836f0988f9ec2211d6820d6e896636bcc940cf15010cf6

build:
  number: 1
  noarch: python
  script: cd python && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >=1.19
    - scipy >=1.6
    - sqlalchemy >=2.0.1
    - platformdirs
    - setuptools
    - packaging

test:
  requires:
    - python >=3.9
  imports:
    - xraydb

about:
  home: https://github.com/xraypy/XrayDB
  license: Public Domain
  license_family: OTHER
  license_file: LICENSE
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
  doc_url: https://xraypy.github.io/XrayDB/
  dev_url: https://github.com/xraypy/XrayDB/

extra:
  recipe-maintainers:
    - newville
